# These are supported funding model platforms

#ko_fi: # Replace with a single Ko-fi username
#tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
liberapay: Kartun83
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: gh/kartun83
